set number relativenumber
set wildmode=longest,list,full
set splitbelow splitright
set laststatus=2
set tabstop=4
set shiftwidth=4
set expandtab
set nofoldenable
set t_Co=256
set background=dark
set termguicolors
set encoding=utf-8


if &term =~ "xterm\\|rxvt"
  " use an orange cursor in insert mode
  let &t_SI = "\<Esc>]12;orange\x7"
  " use a red cursor otherwise
  let &t_EI = "\<Esc>]12;red\x7"
  silent !echo -ne "\033]12;red\007"
  " reset cursor when vim exits
  autocmd VimLeave * silent !echo -ne "\033]112\007"
  " use \003]12;gray\007 for gnome-terminal
endif
map ; :
